/* =====================================================================
   5: GOLD LAYER — BUSINESS VIEWS (STAR SCHEMA)
   =====================================================================
   WHAT THIS DOES:
    Creates three views in the gold schema:
       1. dim_customers  
       2. dim_products   
       3. fact_sales     

    STAR SCHEMA:
       Dimensions (dim_*) describe the "who" and "what"
       Fact (fact_*) records the "how much" and "when"

    Views are used (not tables) because Gold is a presentation layer! 

   PREREQUISITE: 
(Make sure you're granting this access while loggedin as the SILVER user )

       GRANT SELECT ON crm_cust_info     TO gold;
       GRANT SELECT ON crm_prd_info      TO gold;
       GRANT SELECT ON crm_sales_details TO gold;
       GRANT SELECT ON erp_cust_az12     TO gold;
       GRANT SELECT ON erp_loc_a101      TO gold;
       GRANT SELECT ON erp_px_cat_g1v2   TO gold;

(Make sure you're granting this access while loggedin as the SYSTEM user, in the SYSTEM connection you made.)
  
       GRANT CREATE VIEW TO gold;
   ===================================================================== */


/* ---------------------------------------------------------------------
   VIEW 1: gold.dim_customers
   ---------------------------------------------------------------------
   One row per customer, joined across three Silver tables:
      silver.crm_cust_info   (core customer record)
      silver.erp_cust_az12   (birthdate, additional gender)
      silver.erp_loc_a101    (country)

   Business rules:
      CRM is the master source for gender. ERP fills gaps.
      country and gender give 'n/a' if they are missing.
      customer_key is generated by ROW_NUMBER() for surrogate key.
   --------------------------------------------------------------------- */

CREATE OR REPLACE VIEW gold.dim_customers AS
SELECT
    ROW_NUMBER() OVER (ORDER BY ci.cst_id)  AS customer_key,
    ci.cst_id                               AS customer_id,
    ci.cst_key                              AS customer_number,
    ci.cst_firstname                        AS first_name,
    ci.cst_lastname                         AS last_name,
    la.cntry                                AS country,
    ci.cst_marital_status                   AS marital_status,
    CASE
        WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr         -- trust CRM if it knows
        ELSE COALESCE(ca.gen, 'n/a')                        -- otherwise fall back to ERP
    END                                     AS gender,
    ca.bdate                                AS birthdate,
    ci.cst_create_date                      AS create_date
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101  la ON ci.cst_key = la.cid;


/* ---------------------------------------------------------------------
   VIEW 2: gold.dim_products
   ---------------------------------------------------------------------
   One row per CURRENT product, joined across two Silver tables:
      silver.crm_prd_info       (product master)
      silver.erp_px_cat_g1v2    (category / subcategory / maintenance)

   Business rules:
      Only current products appear (prd_end_dt IS NULL).
      cat_id is derived from the first 5 chars of prd_key with '-' replaced by '_'.
      product_key is generated by ROW_NUMBER()
   --------------------------------------------------------------------- */

CREATE OR REPLACE VIEW gold.dim_products AS
SELECT
    ROW_NUMBER() OVER (ORDER BY pn.prd_start_dt, pn.prd_key) AS product_key,
    pn.prd_id        AS product_id,
    pn.prd_key       AS product_number,
    pn.prd_nm        AS product_name,
    pn.cat_id        AS category_id,
    pc.cat           AS category,
    pc.subcat        AS subcategory,
    pc.maintenance   AS maintenance,
    pn.prd_cost      AS cost,
    pn.prd_line      AS product_line,
    pn.prd_start_dt  AS start_date
FROM silver.crm_prd_info pn
LEFT JOIN silver.erp_px_cat_g1v2 pc ON pn.cat_id = pc.id
WHERE pn.prd_end_dt IS NULL;


/* ---------------------------------------------------------------------
   VIEW 3: gold.fact_sales
   ---------------------------------------------------------------------
   One row per sales order line. Joins Silver sales data with both
   dimension views to replace business keys with surrogate keys.

   Business rules:
     - Joins are LEFT JOINS so no sales row is ever dropped.
   --------------------------------------------------------------------- */

CREATE OR REPLACE VIEW gold.fact_sales AS
SELECT
    sd.sls_ord_num   AS order_number,
    pr.product_key   AS product_key,
    cu.customer_key  AS customer_key,
    sd.sls_order_dt  AS order_date,
    sd.sls_ship_dt   AS ship_date,
    sd.sls_due_dt    AS due_date,
    sd.sls_sales     AS sales_amount,
    sd.sls_quantity  AS quantity,
    sd.sls_price     AS price
FROM silver.crm_sales_details sd
LEFT JOIN gold.dim_products  pr ON sd.sls_prd_key = pr.product_number
LEFT JOIN gold.dim_customers cu ON sd.sls_cust_id = cu.customer_id;


/* =====================================================================
   POST-BUILD VALIDATION
   =====================================================================
   Run these AFTER the views are created.
   Expected result shouldl be 0 rows, mapping each sale to a Valid customer! 
   ===================================================================== */

-- CHECK 1: every fact row resolves to a customer
SELECT *
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON c.customer_key = f.customer_key
WHERE c.customer_key IS NULL;

-- CHECK 2: every fact row resolves to a product
SELECT *
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON p.product_key = f.product_key
WHERE p.product_key IS NULL;
